spring.application.name=enterprise-knowledge-assistant

spring.ai.ollama.base-url=https://perception-triple-photographs-author.trycloudflare.com
spring.ai.ollama.chat.options.model=qwen2.5:3b
spring.ai.ollama.chat.options.temperature=0.2
spring.ai.ollama.embedding.options.model=nomic-embed-text

### Vector Chroma DB
spring.ai.vectorstore.chroma.client.host=http://localhost
spring.ai.vectorstore.chroma.client.port=8000
spring.ai.vectorstore.chroma.collection-name=enterprise_documents
spring.ai.vectorstore.chroma.initialize-schema=true


########  myql DB
spring.datasource.url=jdbc:mysql://localhost:3306/enterprise_knowledge_assistant
spring.datasource.username=root
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true